### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by DustyMustard** [DazoTrove/TroveTools.NET#16]
PLATFORM VERSION INFO
    Windows             : 10.0.10586.0 (Win32NT)
    Common Language Runtime     : 4.0.30319.42000
    System.Deployment.dll       : 4.6.1078.0 built by: NETFXREL3STAGE
    clr.dll             : 4.6.1080.0 built by: NETFXREL3STAGE
    dfdll.dll           : 4.6.1038.0 built by: NETFXREL2
    dfshim.dll          : 10.0.10586.0 (th2_release.151029-1700)

SOURCES
    Deployment url          : file:///C:/Users/spale/AppData/Roaming/Microsoft/Windows/Start%20Menu/Programs/Dazo/TroveTools%20.NET.appref-ms%7C
    Deployment Provider url     : https://raw.githubusercontent.com/DazoTrove/TroveTools.NET/master/TroveTools.NET/publish/TroveTools.NET.application

ERROR SUMMARY
    Below is a summary of the errors, details of these errors are listed later in the log.
    \* Activation of C:\Users\spale\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Dazo\TroveTools .NET.appref-ms| resulted in exception. Following failure messages were detected:
        + Activation failed.
        + The system cannot find the file specified. (Exception from HRESULT: 0x80070002)

COMPONENT STORE TRANSACTION FAILURE SUMMARY
    No transaction error was detected.

WARNINGS
    There were no warnings during this operation.

OPERATION PROGRESS STATUS
    \* [6/30/2016 1:51:10 AM] : Activation of C:\Users\spale\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Dazo\TroveTools .NET.appref-ms| has started.
    \* [6/30/2016 1:51:11 AM] : Performing necessary update check as specified by the deployment.

ERROR DETAILS
    Following errors were detected during this operation.
    \* [6/30/2016 1:51:11 AM] System.Deployment.Application.DeploymentException (Activation)
        - Activation failed.
        - Source: System.Deployment
        - Stack trace:
            at System.Deployment.Application.ComponentStore.ActivateApplication(DefinitionAppId appId, String activationParameter, Boolean useActivationParameter)
            at System.Deployment.Application.SubscriptionStore.ActivateApplication(DefinitionAppId appId, String activationParameter, Boolean useActivationParameter)
            at System.Deployment.Application.ApplicationActivator.Activate(DefinitionAppId appId, AssemblyManifest appManifest, String activationParameter, Boolean useActivationParameter)
            at System.Deployment.Application.ApplicationActivator.ProcessOrFollowShortcut(String shortcutFile, String& errorPageUrl, TempFile& deployFile)
            at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
            at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)
        --- Inner Exception ---
        System.IO.FileNotFoundException
        - The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
        - Source: System.Deployment
        - Stack trace:
            at System.Deployment.Application.NativeMethods.CorLaunchApplication(UInt32 hostType, String applicationFullName, Int32 manifestPathsCount, String[] manifestPaths, Int32 activationDataCount, String[] activationData, PROCESS_INFORMATION processInformation)
            at System.Deployment.Application.ComponentStore.ActivateApplication(DefinitionAppId appId, String activationParameter, Boolean useActivationParameter)

COMPONENT STORE TRANSACTION DETAILS
    No transaction information is available.

![1](https://cloud.githubusercontent.com/assets/710289/16482585/49a24098-3e65-11e6-9828-181d303fb713.png)

**Comment by DazoTrove** [comment]
I have not seen this issue before, but found some people who had similar issues with other applications that are also deployed with ClickOnce (a Microsoft .NET deployment technology for publishing applications online).

[This forum post](https://social.msdn.microsoft.com/Forums/windows/en-US/aef681af-d560-4085-9101-eb4573e02028/activation-failed-the-system-cannot-find-the-file-specified-error?forum=winformssetup) suggests a few potential fixes:
1. Clear the ClickOnce application cache by opening the folder: `%LocalAppData%\Apps\2.0` and then deleting the subfolders there. Another site I found recommended running the following command to clear the ClickOnce Cache:
   `rundll32 dfshim CleanOnlineAppCache`
   The next time you run the application it should prompt you to download and install the application. 
2. Uninstall and reinstall the application and see if the issue is resolved.
3. Check whether your antivirus software is quarantining any files during the download process. If it is try excluding the files.

**Comment by DustyMustard** [comment]
Solution via deleting sub-directories.

Thank you.
