### ISSUE TITLE
getting nothing but errors, nothing works

### ISSUE THREAD

**Issue by Xand13** [DazoTrove/TroveTools.NET#41]
2016-10-20 15:40:44 INFO  TroveTools.NET.ViewModel.SettingsViewModel - Loading location settings
2016-10-20 15:40:44 INFO  TroveTools.NET.Model.TroveLocation - Detecting Trove Locations
2016-10-20 15:40:44 INFO  TroveTools.NET.Model.TroveLocation - Searching 10 potential locations
2016-10-20 15:40:45 ERROR TroveTools.NET.ViewModel.SettingsViewModel - Error loading location settings
System.NotSupportedException: This type of CollectionView does not support changes to its SourceCollection from a thread different from the Dispatcher thread.
   at System.Windows.Data.CollectionView.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs args)
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.InsertItem(Int32 index, T item)
   at System.Collections.ObjectModel.Collection`1.Add(T item)
   at TroveTools.NET.ViewModel.SettingsViewModel.LoadData()
2016-10-20 15:40:49 INFO  TroveTools.NET.ViewModel.TrovesaurusViewModel - Loading Trovesaurus news, calendar, and streams data
2016-10-20 15:40:49 INFO  TroveTools.NET.ViewModel.TrovesaurusViewModel - Starting application update timer
2016-10-20 15:40:51 ERROR TroveTools.NET.ViewModel.TrovesaurusViewModel - Error loading Trovesaurus news, calendar or streams
System.NotSupportedException: This type of CollectionView does not support changes to its SourceCollection from a thread different from the Dispatcher thread.
   at System.Windows.Data.CollectionView.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs args)
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.ClearItems()
   at System.Collections.ObjectModel.Collection`1.Clear()
   at TroveTools.NET.ViewModel.TrovesaurusViewModel.LoadData(Object param)
2016-10-20 15:40:51 INFO  TroveTools.NET.ViewModel.GetMoreModsViewModel - Loading mods from Trovesaurus API
2016-10-20 15:40:55 ERROR TroveTools.NET.ViewModel.GetMoreModsViewModel - Error refreshing mods
System.NotSupportedException: This type of CollectionView does not support changes to its SourceCollection from a thread different from the Dispatcher thread.
   at System.Windows.Data.CollectionView.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs args)
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.ClearItems()
   at System.Collections.ObjectModel.Collection`1.Clear()
   at TroveTools.NET.ViewModel.GetMoreModsViewModel.RefreshMods(Object param)
2016-10-20 15:40:55 ERROR TroveTools.NET.ViewModel.GetMoreModsViewModel - Error loading mods from Trovesaurus API
System.NotSupportedException: This type of CollectionView does not support changes to its SourceCollection from a thread different from the Dispatcher thread.
   at System.Windows.Data.CollectionView.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs args)
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.ClearItems()
   at System.Collections.ObjectModel.Collection`1.Clear()
   at TroveTools.NET.ViewModel.GetMoreModsViewModel.BuildTypesCollections()
   at TroveTools.NET.ViewModel.GetMoreModsViewModel.LoadData()
2016-10-20 15:40:56 INFO  TroveTools.NET.ViewModel.MyModsViewModel - Loading my mods
2016-10-20 15:40:56 INFO  TroveTools.NET.Model.TroveMod - Detecting My Mods
2016-10-20 15:40:57 ERROR TroveTools.NET.ViewModel.MyModsViewModel - Error loading my mods
System.NotSupportedException: This type of CollectionView does not support changes to its SourceCollection from a thread different from the Dispatcher thread.
   at System.Windows.Data.CollectionView.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs args)
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.InsertItem(Int32 index, T item)
   at TroveTools.NET.ViewModel.MyModsViewModel.LoadData()
2016-10-20 15:40:59 ERROR TroveTools.NET.ViewModel.MainWindowViewModel - Error loading main window data
System.NotSupportedException: This type of CollectionView does not support changes to its SourceCollection from a thread different from the Dispatcher thread.
   at System.Windows.Data.CollectionView.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs args)
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.InsertItem(Int32 index, T item)
   at TroveTools.NET.ViewModel.ModderToolsViewModel.LoadData()
   at TroveTools.NET.ViewModel.MainWindowViewModel.LoadData(Object param)
2016-10-20 15:41:23 INFO  TroveTools.NET.ViewModel.GetMoreModsViewModel - Loading mods from Trovesaurus API
2016-10-20 15:41:24 ERROR TroveTools.NET.ViewModel.GetMoreModsViewModel - Error refreshing mods
System.NotSupportedException: This type of CollectionView does not support changes to its SourceCollection from a thread different from the Dispatcher thread.
   at System.Windows.Data.CollectionView.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs args)
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.ClearItems()
   at System.Collections.ObjectModel.Collection`1.Clear()
   at TroveTools.NET.ViewModel.GetMoreModsViewModel.RefreshMods(Object param)
2016-10-20 15:42:09 INFO  TroveTools.NET.ViewModel.GetMoreModsViewModel - Loading mods from Trovesaurus API
2016-10-20 15:42:10 ERROR TroveTools.NET.ViewModel.GetMoreModsViewModel - Error refreshing mods
System.NotSupportedException: This type of CollectionView does not support changes to its SourceCollection from a thread different from the Dispatcher thread.
   at System.Windows.Data.CollectionView.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs args)
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.ClearItems()
   at System.Collections.ObjectModel.Collection`1.Clear()
   at TroveTools.NET.ViewModel.GetMoreModsViewModel.RefreshMods(Object param)
2016-10-20 15:44:16 INFO  TroveTools.NET.Model.TroveMod - Loading mod from file: C:\Users\Chris\Downloads\Infineon_Dragon_by_Screamheart_vFinal.zip
2016-10-20 15:44:17 ERROR TroveTools.NET.ViewModel.MyModsViewModel - Error adding mod: C:\Users\Chris\Downloads\Infineon_Dragon_by_Screamheart_vFinal.zip
System.NotSupportedException: This type of CollectionView does not support changes to its SourceCollection from a thread different from the Dispatcher thread.
   at System.Windows.Data.CollectionView.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs args)
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.InsertItem(Int32 index, T item)
   at System.Collections.ObjectModel.Collection`1.Add(T item)
   at CallSite.Target(Closure , CallSite , ObservableCollection`1 , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid2[T0,T1](CallSite site, T0 arg0, T1 arg1)
   at TroveTools.NET.ViewModel.MyModsViewModel.AddMod(String filePath)
2016-10-20 15:53:16 INFO  TroveTools.NET.ViewModel.GetMoreModsViewModel - Loading mods from Trovesaurus API
2016-10-20 15:53:18 ERROR TroveTools.NET.ViewModel.GetMoreModsViewModel - Error refreshing mods
System.NotSupportedException: This type of CollectionView does not support changes to its SourceCollection from a thread different from the Dispatcher thread.
   at System.Windows.Data.CollectionView.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs args)
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.ClearItems()
   at System.Collections.ObjectModel.Collection`1.Clear()
   at TroveTools.NET.ViewModel.GetMoreModsViewModel.RefreshMods(Object param)
2016-10-20 15:53:20 INFO  TroveTools.NET.ViewModel.GetMoreModsViewModel - Loading mods from Trovesaurus API
2016-10-20 15:53:20 ERROR TroveTools.NET.Model.TrovesaurusApi - Error refreshing Trovesaurus mod list
System.Net.WebException: The remote server returned an error: (503) Server Unavailable.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at System.Net.WebClient.DownloadString(String address)
   at TroveTools.NET.Model.TrovesaurusApi.RefreshModList()
2016-10-20 15:53:20 ERROR TroveTools.NET.ViewModel.GetMoreModsViewModel - Error refreshing mods
System.NotSupportedException: This type of CollectionView does not support changes to its SourceCollection from a thread different from the Dispatcher thread.
   at System.Windows.Data.CollectionView.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs args)
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.ClearItems()
   at System.Collections.ObjectModel.Collection`1.Clear()
   at TroveTools.NET.ViewModel.GetMoreModsViewModel.RefreshMods(Object param)
2016-10-20 15:53:20 INFO  TroveTools.NET.ViewModel.MyModsViewModel - Checking all mods for updates
2016-10-20 15:53:31 INFO  TroveTools.NET.ViewModel.GetMoreModsViewModel - Loading mods from Trovesaurus API
2016-10-20 15:53:32 ERROR TroveTools.NET.ViewModel.GetMoreModsViewModel - Error refreshing mods
System.NotSupportedException: This type of CollectionView does not support changes to its SourceCollection from a thread different from the Dispatcher thread.
   at System.Windows.Data.CollectionView.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs args)
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.ClearItems()
   at System.Collections.ObjectModel.Collection`1.Clear()
   at TroveTools.NET.ViewModel.GetMoreModsViewModel.RefreshMods(Object param)
2016-10-20 15:53:32 INFO  TroveTools.NET.ViewModel.MyModsViewModel - Checking all mods for updates
2016-10-20 15:54:01 INFO  TroveTools.NET.ViewModel.GetMoreModsViewModel - Loading mods from Trovesaurus API
2016-10-20 15:54:06 ERROR TroveTools.NET.ViewModel.GetMoreModsViewModel - Error refreshing mods
System.NotSupportedException: This type of CollectionView does not support changes to its SourceCollection from a thread different from the Dispatcher thread.
   at System.Windows.Data.CollectionView.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs args)
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.ClearItems()
   at System.Collections.ObjectModel.Collection`1.Clear()
   at TroveTools.NET.ViewModel.GetMoreModsViewModel.RefreshMods(Object param)
2016-10-20 15:54:06 INFO  TroveTools.NET.ViewModel.GetMoreModsViewModel - Loading mods from Trovesaurus API
2016-10-20 15:54:06 ERROR TroveTools.NET.ViewModel.GetMoreModsViewModel - Error refreshing mods
System.NotSupportedException: This type of CollectionView does not support changes to its SourceCollection from a thread different from the Dispatcher thread.
   at System.Windows.Data.CollectionView.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs args)
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.ClearItems()
   at System.Collections.ObjectModel.Collection`1.Clear()
   at TroveTools.NET.ViewModel.GetMoreModsViewModel.RefreshMods(Object param)
2016-10-20 15:54:06 INFO  TroveTools.NET.ViewModel.GetMoreModsViewModel - Loading mods from Trovesaurus API
2016-10-20 15:54:07 ERROR TroveTools.NET.ViewModel.GetMoreModsViewModel - Error refreshing mods
System.NotSupportedException: This type of CollectionView does not support changes to its SourceCollection from a thread different from the Dispatcher thread.
   at System.Windows.Data.CollectionView.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs args)
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.ClearItems()
   at System.Collections.ObjectModel.Collection`1.Clear()
   at TroveTools.NET.ViewModel.GetMoreModsViewModel.RefreshMods(Object param)
2016-10-20 15:54:07 INFO  TroveTools.NET.ViewModel.GetMoreModsViewModel - Loading mods from Trovesaurus API
2016-10-20 15:54:08 ERROR TroveTools.NET.ViewModel.GetMoreModsViewModel - Error refreshing mods
System.NotSupportedException: This type of CollectionView does not support changes to its SourceCollection from a thread different from the Dispatcher thread.
   at System.Windows.Data.CollectionView.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs args)
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.ClearItems()
   at System.Collections.ObjectModel.Collection`1.Clear()
   at TroveTools.NET.ViewModel.GetMoreModsViewModel.RefreshMods(Object param)

**Comment by DazoTrove** [comment]
I haven't seen this bug happen before when I have been testing it, but I have researched the error message and am going to update TroveTools.NET to hopefully fix this issue.

**Comment by DazoTrove** [comment]
Let me know if this issue isn't fixed after you update to v1.1.9.7. If it isn't fixed we can re-open this issue.
