### ISSUE TITLE
NullReferenceException in TroveTools.NET.Model.ApplicationDetails.UpdateAvailable

### ISSUE THREAD

**Issue by DazoTrove** [DazoTrove/TroveTools.NET#52]
```
   at System.Deployment.Application.DeploymentManager.BindCoreWithAppId(Boolean blocking, FileStream& refTransaction, String& productName)
   at System.Deployment.Application.DeploymentManager.BindCore(Boolean blocking, TempFile& tempDeploy, TempDirectory& tempAppDir, FileStream& refTransaction, String& productName)
   at System.Deployment.Application.DeploymentManager.Bind()
   at System.Deployment.Application.ApplicationDeployment.CheckForDetailedUpdate(Boolean persistUpdateCheckResult)
   at TroveTools.NET.Model.ApplicationDetails.UpdateAvailable()
```

**Comment by DazoTrove** [comment]
This issue wasn't fixed with the first update made. I think the issue may be an automatic check for updates after the user has already downloaded the new update but not restarted the application yet.

From [a forum post on MSDN](https://social.msdn.microsoft.com/Forums/windows/en-US/a329fd10-da8f-40a6-86ff-4430e0036110/exception-when-calling-checkfordetailedupdate?forum=winformssetup)

> CheckForDetailedUpdate just checks for it. If you then perform the update, it doesn't apply until you restart the application. If you have a pending update, you can't check for updates again -- this might be what's causing your problem.
