### ISSUE TITLE
InvalidOperationException in TroveTools.NET.ViewModel.GetMoreModsViewModel.LoadData

### ISSUE THREAD

**Issue by DazoTrove** [DazoTrove/TroveTools.NET#58]
The calling thread cannot access this object because a different thread owns it.

```
   at System.Windows.Threading.Dispatcher.VerifyAccess()
   at System.Windows.DependencyObject.GetValue(DependencyProperty dp)
   at System.Windows.Data.CollectionViewSource.get_CollectionView()
   at TroveTools.NET.ViewModel.GetMoreModsViewModel.LoadData()
```

**Comment by DazoTrove** [comment]
When implementing issue #4 I will be able to address this Dispatcher error better
