### ISSUE TITLE
Can't install Mods Win 10 

### ISSUE THREAD

**Issue by Bulldozer2k** [DazoTrove/TroveTools.NET#67]
Hi,

I have been using Trove Tools for a while now, and I love it, and promote it on my Stream.  I built a new gaming PC last night and when I try to install any mod, I get the same error.  I have reinstalled, uninstalled, deleted, recreated folders. 

The error is always the same:
2017-03-15 18:07:32 INFO  TroveTools.NET.ViewModel.SettingsViewModel - Saving location settings
2017-03-15 18:07:38 INFO  TroveTools.NET.Model.TroveMod - Downloading mod: Customized VFX for Shadow/Radiant/Stellar
2017-03-15 18:07:47 ERROR TroveTools.NET.Model.TroveMod - Error downloading mod: Customized VFX for Shadow/Radiant/Stellar
System.Net.WebException: Too many automatic redirections were attempted.
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at System.Net.WebClient.DownloadFile(String address, String fileName)
   at TroveTools.NET.Model.TrovesaurusApi.DownloadMod(TroveMod mod, String fileId)
   at TroveTools.NET.Model.TrovesaurusApi.DownloadMod(TroveMod mod)
   at TroveTools.NET.Model.TroveMod.UpdateMod()

This happens for any mod I try to download.  I did check the MODs folder, after each attempt, it is still empty.

Thank for looking into and helping solve this issue.
MODS i have tried Boss Health, Clock, Mini boss radar, various VFX mods, Waypoints edition, etc. to name a few.

**Comment by AlgebraPlayzTrove** [comment]
Hi, um when I use trovetools.net on my windows 10 PC it says verifying give it a moment i waited for 1 hour it didn't start can you help me out

**Comment by Bulldozer2k** [comment]
Hi,

For my install, I uninstalled glyph and trove, then trove tools.  I then
reinstalled all of them.  What you need to be careful with, trove has a
MODS folder separate from trove tools directory.  If you reinstall, and all
of you mods are there already, uninstall them manually through the trove
tools app, and reinstall them.

For some reason, they appear installed in trove tools, but they do not copy
over into the Glyph Trove mods folder.
